name: trimli

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${DB_USER:-myslq}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-mysql_root}
      MYSQL_DATABASE: ${DB_NAME:-default}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u${DB_USER:-myslq}',
          '-p${DB_PASSWORD:-mysql}',
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:
